export const PROTOCOLS = [
    {
        id: 'zest',
        name: 'Zest Protocol',
        type: 'Lending',
        apy: '8.2',
        tvl: '$48.2M',
        asset: 'sBTC',
        risk: 'Low',
        description: 'Lend and borrow Bitcoin-backed assets with transparent on-chain rates.',
        url: 'https://zestprotocol.com',
        color: '#F7931A',
        icon: '🏦',
    },
    {
        id: 'bitflow',
        name: 'Bitflow',
        type: 'DEX',
        apy: '12.4',
        tvl: '$31.7M',
        asset: 'sBTC/STX',
        risk: 'Medium',
        description: 'Decentralized exchange aggregator for the best sBTC swap rates on Stacks.',
        url: 'https://bitflow.finance',
        color: '#5546FF',
        icon: '🔄',
    },
    {
        id: 'alex',
        name: 'ALEX Lab',
        type: 'DEX',
        apy: '15.1',
        tvl: '$124.5M',
        asset: 'sBTC/STX',
        risk: 'Medium',
        description: 'The leading Bitcoin DeFi super app — swap, earn, and launch on Stacks.',
        url: 'https://alexlab.co',
        color: '#00D4AA',
        icon: '⚡',
    },
    {
        id: 'hermetica',
        name: 'Hermetica',
        type: 'Yield',
        apy: '18.7',
        tvl: '$22.1M',
        asset: 'sBTC',
        risk: 'High',
        description: 'Bitcoin-backed synthetic dollar yielding protocol built on Stacks.',
        url: 'https://hermetica.fi',
        color: '#9B59B6',
        icon: '🔮',
    },
    {
        id: 'stackingdao',
        name: 'StackingDAO',
        type: 'Stacking',
        apy: '9.5',
        tvl: '$89.3M',
        asset: 'STX',
        risk: 'Low',
        description: 'Liquid stacking protocol — stack STX and keep liquidity with stSTX.',
        url: 'https://stackingdao.com',
        color: '#E74C3C',
        icon: '🥩',
    },
    {
        id: 'granite',
        name: 'Granite',
        type: 'Lending',
        apy: '7.8',
        tvl: '$18.6M',
        asset: 'sBTC',
        risk: 'Low',
        description: 'Borrow stablecoins against your Bitcoin collateral on Stacks.',
        url: 'https://granite.finance',
        color: '#95A5A6',
        icon: '🪨',
    },
    {
        id: 'velar',
        name: 'Velar',
        type: 'DEX',
        apy: '11.3',
        tvl: '$14.2M',
        asset: 'sBTC/STX',
        risk: 'Medium',
        description: 'Perpetuals and spot trading protocol on Bitcoin L2 via Stacks.',
        url: 'https://velar.co',
        color: '#3498DB',
        icon: '📈',
    },
];

export const RISK_STYLES = {
    Low: 'text-green-500',
    Medium: 'text-yellow-500',
    High: 'text-red-500',
};

export const FILTER_TYPES = ['All', 'Lending', 'DEX', 'Yield', 'Stacking'];
